.github/workflows/release_python.yml
python/MANIFEST.in

- OMMXのPythonパッケージ部分をリリースするCIを設定しました
- Pythonパッケージ部分にバイナリ等が含まれないのでsdistでの配布を行う方針を取りました
- MANIFEST.in でsdistにtestsディレクトリが含まれないようにしています

Add release workflow for python.

---

proto/ommx/v1/solution.proto
python/ommx/v1/solution_pb2.py
python/ommx/v1/solution_pb2.pyi
rust/ommx/src/ommx.v1.rs

Fix of #32, split from #34
- Make `RawSolution` "pure" solution state

Move feasible and optimal fields to Solution message instead of RawSolution

---

proto/ommx/v1/solution.proto
python/ommx/testing.py
python/ommx/v1/solution_pb2.py
python/ommx/v1/solution_pb2.pyi
rust/ommx/src/ommx.v1.rs

- `RawSolution` is renamed into `State`
- `SolutionList` and `RawSolutionList` are removed

Rename `RawSolution` to `State`

---

proto/ommx/v1/quadratic.proto
python/ommx/v1/quadratic_pb2.pyi
rust/ommx/src/ommx.v1.rs

Add document for quadratic function

---

python/ommx-python-mip-adaptor/README.md
python/ommx-python-mip-adaptor/ommx_python_mip_adapter/adapter.py
python/ommx-python-mip-adaptor/tests/test_integration.py
python/ommx-python-mip-adaptor/tests/test_model_to_instance.py
python/ommx/ommx/v1/__init__.py
python/ommx/tests/test_function.py
python/ommx/tests/test_import.py

- Add `ommx.v1.Linear` with `__add__`, `__sub__`, and other operators. Using them, we can create an instance like:
```python
x1 = DecisionVariable.integer(1, lower=LOWER_BOUND, upper=UPPER_BOUND)
x2 = DecisionVariable.continuous(2, lower=LOWER_BOUND, upper=UPPER_BOUND)
ommx_instance = Instance.from_components(
decision_variables=[x1, x2],
objective=-x1 - x2,
constraints=[
3 * x1 - x2 <= 6,
-x1 + 3 * x2 <= 6,
],
sense=Instance.MINIMIZE,
)
```

Minimal modeler API to create `ommx.v1.Function`

---

proto/ommx/v1/constraint.proto
proto/ommx/v1/decision_variables.proto
python/ommx-python-mip-adapter/ommx_python_mip_adapter/adapter.py
python/ommx-python-mip-adapter/tests/test_model_to_instance.py
python/ommx/ommx/v1/__init__.py
python/ommx/ommx/v1/constraint_pb2.py
python/ommx/ommx/v1/constraint_pb2.pyi
python/ommx/ommx/v1/decision_variables_pb2.py
python/ommx/ommx/v1/decision_variables_pb2.pyi
rust/ommx/src/evaluate.rs
rust/ommx/src/ommx.v1.rs
rust/ommx/src/random.rs

- `DecisionVariable.Description` and `ConstraintDescription` are flattened.
- New `description` fields are added to `DecisionVariable` and `Constraint` to write long human-readable description
- `subscripts` are split from `parameters` in `DecisionVariable`

Flatten descriptions of decision variables and constraints

---

python/ommx-python-mip-adapter/docs/source/conf.py
python/ommx-python-mip-adapter/ommx_python_mip_adapter/__init__.py
python/ommx-python-mip-adapter/ommx_python_mip_adapter/ommx_to_python_mip.py
python/ommx-python-mip-adapter/ommx_python_mip_adapter/python_mip_to_ommx.py
python/ommx/docs/source/conf.py
python/ommx/ommx/v1/__init__.py

- New function `solve` in `ommx_python_mip_adapter` which takes `ommx.v1.Instance` and returns `ommx.v1.Solution`. This allow us to solve the problem without touching `mip` components.
- Add doctest for `solve` and `ommx.v1.Instance`

`ommx_python_mip_adapter.solve`

---

proto/ommx/v1/solution.proto
python/ommx-python-mip-adapter/ommx_python_mip_adapter/ommx_to_python_mip.py
python/ommx/ommx/v1/solution_pb2.py
python/ommx/ommx/v1/solution_pb2.pyi
rust/ommx/src/evaluate.rs
rust/ommx/src/ommx.v1.rs

- ⚠️  `option bool optimal` is encoded into single `bool` in Python, i.e. `None` and `False` are not distinguished. Instead, this PR introduces `Optimality` enum to explicitly distinguish them. 
- To represent the error case of solvers, `ommx.v1.Result` has been introduced. `ommx_python_mip_adapter.solve` returns this object.

Introduce `ommx.v1.Result` and `Optimality` enum

---

notebooks/artifact.ipynb
notebooks/message.ipynb

Add a button to open colab, like [![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Jij-Inc/ommx/blob/main/notebooks/artifact.ipynb)

Open notebook on Colab

---

DEVELOPMENT.md
python/ommx-python-mip-adapter/docs/source/conf.py
python/ommx-python-mip-adapter/pyproject.toml
python/ommx/docs/source/conf.py
python/ommx/ommx/v1/__init__.py
python/ommx/pyproject.toml

Issue: https://github.com/Jij-Inc/ommx/issues/117

Fix the argument of `Quadratic`: `raws` -> `rows`

---

python/ommx/ommx/v1/__init__.py

`Solution`の目的関数の値を`raw`プロパティ経由でしか参照できないのが不便だったため、`objective`プロパティを追加しました。また、`Instance`, `Solution`, `DecisionVariable`についてprotobufスキーマ上では存在しているがプロパティとして実装されていないものがいくつかあったので、それらについても追加しました。

Add more properties to `Instance`, `Solution`, and `DecisionVariable`

---

Cargo.lock
python/ommx/pyproject.toml

Bump the Python package `ommx` from 1.4.0 to 1.4.1.

Bump OMMX Python SDK from 1.4.0 to 1.4.1

---

.github/workflows/python.yml
.github/workflows/release_python.yml
.gitignore
Taskfile.yml
python/ommx-pyscipopt-adapter/README.md
python/ommx-pyscipopt-adapter/ommx_pyscipopt_adapter/__init__.py
python/ommx-pyscipopt-adapter/ommx_pyscipopt_adapter/adapter.py
python/ommx-pyscipopt-adapter/ommx_pyscipopt_adapter/exception.py
python/ommx-pyscipopt-adapter/ommx_pyscipopt_adapter/ommx_to_pyscipopt.py
python/ommx-pyscipopt-adapter/pyproject.toml
python/ommx-pyscipopt-adapter/tests/test_error.py
python/ommx-pyscipopt-adapter/tests/test_integration.py
python/ommx-python-mip-adapter/docs/source/conf.py
python/ommx-python-mip-adapter/pyproject.toml
python/ommx/docs/source/conf.py
python/ommx/pyproject.toml

- `ommx-pyscipopt-adapter` を追加しました
- 追加に伴い、Taskfile.ymlに `ommx-pyscipopt-adapter` 用のコマンドを追加しました
- 追加に伴い、GitHubActionsに `ommx-pyscipopt-adapter` をテストするCI、PyPIへリリースするCDを設定しました

Add `ommx-pyscipopt-adapter`

---

python/ommx/ommx/artifact.py

Store JSON with `application/json` media type

`ArtifactBuilder.add_json` / `Artifact.get_json`

---

proto/ommx/v1/decision_variables.proto
python/ommx/ommx/v1/decision_variables_pb2.py
python/ommx/ommx/v1/decision_variables_pb2.pyi
rust/ommx/src/convert/decision_variable.rs
rust/ommx/src/evaluate.rs
rust/ommx/src/mps/convert.rs
rust/ommx/src/ommx.v1.rs

This field stores the value within the `partial_evaluate`

`substituted_value` in `ommx.v1.DecisionVariable`

---

rust/ommx/src/convert.rs
rust/ommx/src/convert/decision_variable.rs
rust/ommx/src/convert/parameter.rs
rust/ommx/src/convert/parametric_instance.rs

- Implement `Add` and `Mul` for `DecisionVariable` and `Parameter`
- `impl Arbitrary for ParametricInstance`

Modeler API of `ommx::v1::DecisionVariable` in Rust SDK

---

rust/ommx/src/convert.rs
rust/ommx/src/convert/decision_variable.rs
rust/ommx/src/convert/format.rs
rust/ommx/src/convert/function.rs
rust/ommx/src/convert/instance.rs
rust/ommx/src/convert/parametric_instance.rs
rust/ommx/src/convert/polynomial.rs
rust/ommx/src/convert/quadratic.rs
rust/ommx/src/convert/sorted_ids.rs

QUBO and PUBO format output

---

python/ommx/ommx/v1/__init__.py

This is not useful for most cases.

Use default `__repr__` for `DecisionVariable`

---

python/ommx-pyscipopt-adapter/pyproject.toml
python/ommx-python-mip-adapter/pyproject.toml
python/ommx/pyproject.toml

#187 is enough for bumping up the minor version.

Python SDK 1.5.0

---

rust/ommx/src/convert/instance.rs

Split from #200 
Breaking change
---------
- Rename `Instance::check_decision_variables` to `Instance::validate_decision_variable_ids` to make the objective clear.
other changes
--------------
- Create `Instance::validate` for checking all
- Add `Instance::validate_constraint_ids` to check constraint ID duplication including removed constraints.

Revise `Instance::validate*` APIs

---

python/ommx/ommx/v1/__init__.py

In #197, `__all__` is added in `ommx.v1` module, but this makes sphinx document broken. This PR fix it.

Revise sphinx document

---

.github/actions/setup-test-environment/action.yml
.github/workflows/doc.yml
.github/workflows/python.yml
.github/workflows/release_python.yml
python/ommx-pyscipopt-adapter/pyproject.toml
python/ommx-python-mip-adapter/pyproject.toml
python/ommx/pyproject.toml
python/set-version.py

https://devguide.python.org/versions/

Drop Python 3.8 because it has been ended at 2024/10/7

---

python/ommx/ommx/artifact.py
python/ommx/ommx/v1/__init__.py

Restore `Solution.annotations` in `Artifact.get_solution`

---

python/ommx/ommx/v1/__init__.py

`Function.terms` and related properties

---

rust/ommx/src/convert/instance.rs

Bug fix of `as_{qubo,pubo}_format` as it does not sum up the same terms.

---

rust/ommx/src/convert/instance.rs

Remove zero coefficients in `Instance::as_{pubo,qubo}_format`

---

python/ommx/ommx/v1/__init__.py

`Solution.extract_{decision_variables,constraints}` are added. They returns `dict[subscript, value]`.

Extract values from `ommx.v1.Solution` with `name` and `subscripts` annotations

---

.github/actions/setup-test-environment/action.yml
.github/dependabot.yml
.github/workflows/python.yml
.github/workflows/release_python.yml
Taskfile.yml
python/ommx-openjij-adapter/ommx_openjij_adapter/__init__.py
python/ommx-openjij-adapter/tests/test_sample.py

- Negate objective **after** converted QUBO if `sense == MAXIMIZE`
- Update CI setting including release

Support maximization problem for OpenJij Adapter

---

docs/en/introduction.ipynb

This pull request updates the documentation to explain in greater detail of introduction. 
The introduction file `docs/en/introduction.ipynb`.

Enhance Documentation for docs/en/introduction.ipynb

---

python/ommx/ommx/v1/__init__.py

Initializers for `Parameter` and `ParametricInstance`

---

python/ommx-tests/tests/test_instance.py
python/ommx/ommx/v1/__init__.py

Example
----------
```python
x = [DecisionVariable.binary(i) for i in range(3)]
instance = Instance.from_components(
decision_variables=x,
objective=sum(x),
constraints=[],
sense=Instance.MAXIMIZE,
)
assert instance.objective.almost_equal(Function(sum(x)))
instance.objective = x[1]
assert instance.objective.almost_equal(Function(x[1]))
```

Setter for Instance.objective

---

Cargo.lock
Cargo.toml

Revert #303, bump up to 2.0.0-rc.2

Rust SDK 2.0.0-rc.2

---

python/ommx/ommx/v1/__init__.py

Change default value `inequality_integer_slack_max_range = 31`

---

.github/workflows/doc.yml
docs/en/_config.yml
docs/ja/_config.yml

Set Google Analytics (GA4) tracking code in Jupyter book

---

rust/ommx/src/coefficient.rs
rust/ommx/src/lib.rs
rust/ommx/src/parse.rs

`Offset` has been introduced in https://github.com/Jij-Inc/ommx/pull/428 with `Coefficient`, but it is not used now.

Drop `Offset`

---

python/ommx/src/evaluate.rs
python/ommx/src/instance.rs
python/ommx/src/message.rs
rust/ommx/benches/evaluate.rs
rust/ommx/benches/partial_evaluate.rs
rust/ommx/src/atol.rs
rust/ommx/src/bound.rs
rust/ommx/src/coefficient.rs
rust/ommx/src/constraint/approx.rs
rust/ommx/src/constraint/evaluate.rs
rust/ommx/src/evaluate.rs
rust/ommx/src/function/approx.rs
rust/ommx/src/function/evaluate.rs
rust/ommx/src/instance/analysis.rs
rust/ommx/src/instance/approx.rs
rust/ommx/src/lib.rs
rust/ommx/src/macros.rs
rust/ommx/src/mps/tests.rs
rust/ommx/src/polynomial_base/approx.rs
rust/ommx/src/polynomial_base/evaluate.rs
rust/ommx/src/v1_ext/constraint.rs
rust/ommx/src/v1_ext/function.rs
rust/ommx/src/v1_ext/instance.rs
rust/ommx/src/v1_ext/linear.rs
rust/ommx/src/v1_ext/parametric_instance.rs
rust/ommx/src/v1_ext/polynomial.rs
rust/ommx/src/v1_ext/quadratic.rs
rust/ommx/src/v1_ext/sample_set.rs

`ATol` type for absolute tolerrance

---

docs/en/_toc.yml
docs/ja/_toc.yml

Rendered:
- English: https://ommx-en-book--477.org.readthedocs.build/en/477/introduction.html
- Japanese: https://ommx-ja-book--477.org.readthedocs.build/ja/477/introduction.html

Add link to DeepWiki

---

python/ommx-openjij-adapter/ommx_openjij_adapter/__init__.py
python/ommx/ommx/adapter.py

Remove the following methods from `SamplerAdapter` and implement them in `OMMXOpenJijSAAdapter`
- `solve`
- `solver_input`
- `decode`

Remove default `solve` implementation in `SamplerAdapter`

---

rust/ommx/src/constraint.rs
rust/ommx/src/instance.rs
rust/ommx/src/instance/error.rs
rust/ommx/src/instance/setter.rs

#553 does not keep invariant of `ommx::Instance`

Dependent variables cannot be used 
