.github/workflows/release_python.yml

Add permission to Publish Python Package

---

proto/ommx/v1/instance.proto
python/ommx/v1/instance_pb2.py
python/ommx/v1/instance_pb2.pyi
python/pyproject.toml
rust/Cargo.lock
rust/ommx/Cargo.toml
rust/ommx/src/ommx.v1.rs

OMMX::Instanceが意味する最適化問題が最小化問題であるか最大化問題であるかが判別できないという課題があった為、senseを追加しました。
こちらの変更後、Pythonパッケージをv0.1.2として、Rustクレートをv0.1.1としてリリースしても良いでしょうか？（バージョニングは適切でしょうか？）

Add `sense` field to `Instance`

---

.gitattributes
python/ommx/testing.py

Split from #32 
- `ommx.testing.SingleFeasibleLPGenerator` should returns `Instance` directly because this is for Python users.

Return `Instance` and `Solution` objects instead of `bytes`

---

proto/ommx/v1/constraint.proto
proto/ommx/v1/decision_variables.proto
proto/ommx/v1/solution.proto
python/ommx/v1/constraint_pb2.py
python/ommx/v1/constraint_pb2.pyi
python/ommx/v1/decision_variables_pb2.py
python/ommx/v1/decision_variables_pb2.pyi
python/ommx/v1/solution_pb2.py
python/ommx/v1/solution_pb2.pyi
rust/ommx/src/ommx.v1.rs

- Move `EvaluatedConstraint` message from `Solution.*` to `ommx.v1.*`
- Move `Constraint.Description` into `ommx.v1.ConstraintDescription`, and revise `forall` field into `parameters` which stores string-string map instead of `repeated int64`
- Add `decision_variables` in `Solution` message

Store descriptions of decision variables and constraints in Solution

---

.github/workflows/cli.yml
Cargo.lock
Cargo.toml
python/Cargo.toml
rust/ommx/Cargo.toml
rust/ommx/examples/artifact_archive.rs
rust/ommx/examples/create_artifact.rs
rust/ommx/examples/pull_artifact.rs
rust/ommx/src/artifact.rs
rust/ommx/src/bin/ommx.rs
rust/ommx/src/evaluate.rs
rust/ommx/src/lib.rs
rust/protogen/Cargo.toml

- Bump up crate version 0.3.0
- `[workspace.package]` is introduced, and use it in all crates, i.e. `ommx`, `protogen`, and `_ommx_rust` crates.
- More documents
- `env_logger` is added to `ommx` executable and examples
- Add `examples/pull_artifact.rs`

Ready for releasing Rust SDK 0.3.0

---

ARTIFACT.md
notebooks/artifact.ipynb
python/ommx/artifact.py
python/ommx/v1/__init__.py
python/pyproject.toml

- Annotations like `org.ommx.v1.instance.title` are now stored in `ommx.v1.Instance` Python object as attributes.
- `ArtifactBuilder.add_instance` now does not take `annotations` argument. Annotations are set through the above `Instance` class

Store annotations in `ommx.v1.{Instance, Solution}` Python objects

---

.github/workflows/release_python.yml
.github/workflows/release_rust.yml
python/pyproject.toml

From 0.3.0, the Python SDK becomes Rust/Python mixed project, and release flow has changed.

Build wheels for release

---

python/ommx/artifact.py

- `ArtifactBuilder.add_ndarray` is introduced. It serializes given `numpy.ndarray` into NPY file format by `numpy.save`, and stores this binary with `application/vnd.numpy` media type

NumPy support in OMMX Artifact

---

.github/workflows/python.yml
python/ommx-python-mip-adaptor/README.md
python/ommx-python-mip-adaptor/ommx_python_mip_adapter/adapter.py
python/ommx-python-mip-adaptor/tests/test_instance_to_model.py
python/ommx/ommx/testing.py
python/ommx/ommx/v1/__init__.py

- `Instance.from_components` is introduced to create in 0.2.0 style before wrapper class `ommx.v1.Instance` has been introduced in #44.
- This reverts most of dbd99c55bab00754360a013386421d55236f038e changes to update `ommx-python-mip-adaptor`

Better constructor APIs for creating `ommx.v1.Instance`

---

proto/ommx/v1/constraint.proto
python/ommx-python-mip-adapter/ommx_python_mip_adapter/ommx_to_python_mip.py
python/ommx/ommx/v1/constraint_pb2.py
python/ommx/ommx/v1/constraint_pb2.pyi
rust/ommx/src/evaluate.rs
rust/ommx/src/ommx.v1.rs

- `EvaluatedConstraint.dual_variable` to store Lagrangian dual variables
- `ommx_python_mip_adapter.solve` stores the dual variable if `mip.Constr.pi` exists.

Store dual variable in `EvaluatedConstraint`

---

python/ommx-python-mip-adapter/pyproject.toml
python/ommx-python-mip-adapter/tests/test_constant_constraint.py

Constraint without any decision variable like following causes segmentation fault in CBC solver with Python-MIP 1.15. https://github.com/Jij-Inc/ommx/actions/runs/9698846012/job/26766373894
```python
x = DecisionVariable.continuous(0)
instance = Instance.from_components(
decision_variables=[x],
objective=x,
constraints=[
Linear(terms={}, constant=1) >= 0,
x <= 1,
],
sense=Instance.MAXIMIZE,
)
```
This has been reported in https://github.com/coin-or/python-mip/issues/213 and some linked issues, and fixed in https://github.com/coin-or/python-mip/pull/237.
We use latest commit of Python-MIP https://github.com/coin-or/python-mip/commit/0ccb81115543e737ab74a4f1309891ce5650c8d5 until the next version is released https://github.com/coin-or/python-mip/issues/384

Constant constraints

---

rust/ommx/src/evaluate.rs

Inequality constraint `f(x) <= 0` is checked as the evaluated value of `f(x)` is larger than zero, but it should be larger than tolerance `>= 1e-6`

Feasibility condition for inequality is too strict

---

proto/ommx/v1/constraint.proto
python/ommx/ommx/v1/constraint_pb2.py
python/ommx/ommx/v1/constraint_pb2.pyi
rust/ommx/src/evaluate.rs
rust/ommx/src/ommx.v1.rs
rust/ommx/src/random.rs

Split from #88 
It is rather natural also for `Constraint` message to use `subscripts` for integer parameter and `parameters` for string parameters as `DecisionVariable` does.

Add `subscripts` field into `Constraint` message

---

.github/release.yml
.github/workflows/python.yml
.github/workflows/release_python.yml
python/ommx-python-mip-adapter/pyproject.toml
python/ommx-python-mip-adapter/tests/test_constant_constraint.py
python/ommx/pyproject.toml

Partially reverts #82 with `pytest.mark.skip`

Do not use git dependencies for Python-MIP to release 1.0.0

---

.github/workflows/python.yml
.github/workflows/release_python.yml
python/ommx-python-mip-adapter/pyproject.toml
python/ommx/pyproject.toml

Note that `ommx-python-mip-adapter` does not work with Python 3.12 because Python-MIP does not supports 3.12.

Add support for Python 3.12

---

python/ommx/ommx/v1/__init__.py
python/ommx/tests/test_function.py

Partially reverts #94
- `Function.__init__` is enough for converting `Linear`, `Quadratic`, and others into `Function`. `ommx._ommx_rust.Function.from_linear` and others are kept for future use.

Remove `Function.from_linear` and others, use `__init__` instead

---

rust/ommx/src/convert/format.rs
rust/ommx/src/convert/linear.rs

Split from #134 
- Implementation of `Display` trait is incorrect when the constraint is `1.0`

Fix `impl Display` and `__repr__` for `Linear` and other `Function`s

---

proto/ommx/v1/constraint.proto
python/ommx/ommx/v1/__init__.py
python/ommx/ommx/v1/constraint_pb2.py
python/ommx/ommx/v1/constraint_pb2.pyi
rust/ommx/src/mps/convert.rs
rust/ommx/src/ommx.v1.rs

- Add optional fields, `dual_variable` and `penalty_weight` in `Constraint` message.
- This will be used in #143 to create unconstrained problem. #143 will support two way to create QUBO and PUBO, penalty method and augmented Lagrangian method
For a problem 
$$
\begin{align*}
\min & f(x) \\
\text{s.t.} & g(x) = 0
\end{align*}
$$
- Penalty method try to minimize $f(x) + \rho |g(x)|^2$, where $\rho$ is called penalty weight.
- Augmented Lagrangian method try to minimize $f(x) + \lambda g(x) + \rho |g(x)|^2$, where $\lambda$ is current dual variable and $\rho$ is also a penalty weight.
`dual_variable` field is intended to store $\lambda$, and `penalty_weight` stores $\rho$ in this sense.

`dual_variable` and `penalty_weight` in `Constraint` message for QUBO

---

python/ommx-python-mip-adapter/README.md
python/ommx-python-mip-adapter/docs/source/conf.py
python/ommx-python-mip-adapter/ommx_python_mip_adapter/__init__.py
python/ommx-python-mip-adapter/ommx_python_mip_adapter/ommx_to_python_mip.py
python/ommx-python-mip-adapter/ommx_python_mip_adapter/python_mip_to_ommx.py
python/ommx-python-mip-adapter/pyproject.toml
python/ommx-python-mip-adapter/tests/test_integration.py
python/ommx/docs/source/conf.py
python/ommx/pyproject.toml

- 変更前の時点では、`model_to_solution` 関数が`ommx.v1.State`を返している状態だったため、関数名を`model_to_state`に変更しました
- `ommx.v1.Solution`を返す関数`model_to_solution`を新しく実装しました
- この変更に伴い、`solve`関数の内部処理を新規実装した`model_to_solution`に置き換えました
`model_to_solution`関数の破壊的変更のため、最低でもマイナーバーションを上げる必要があります。

Add `model_to_solution` and `model_to_state`.

---

.github/actions/setup-test-environment/action.yml
.github/workflows/python.yml
.github/workflows/rust.yml
python/ommx-python-mip-adapter/pyproject.toml
python/ommx/pyproject.toml
ruff.toml

- Gather common setups in jobs into `.github/actions/setup-test-environment` 
- Upgrade ruff to 0.7.4
- Replace `pip install -ve python/ommx[dev]` by `pip install ruff` for some cases

Custom GitHub Actions for install executables

---

rust/ommx/src/convert.rs
rust/ommx/src/convert/function.rs
rust/ommx/src/convert/linear.rs
rust/ommx/src/convert/polynomial.rs
rust/ommx/src/convert/quadratic.rs
rust/ommx/src/convert/state.rs
rust/ommx/src/evaluate.rs

Split from #146 
- Substitute decision variables partially. For example, substitute $x_1 = 1$ to $x_1 x_2 + x_1 + 1$ yielding $x_2 + 2$

Partial evaluation of `ommx.v1.Function`

---

.github/actions/setup-test-environment/action.yml
.github/workflows/release_python.yml
Taskfile.yml
python/ommx-python-mip-adapter/docs/source/conf.py
python/ommx-python-mip-adapter/pyproject.toml
python/ommx/docs/source/conf.py
python/ommx/pyproject.toml
python/set-version.py

Add `python/set-version.py` to update versions of Python SDK and adapters. To update specific version (with `uv`):
```shell
uv run python/set-version.py 1.4.2
```
To bump up patch version:
```shell
uv run python/set-version.py
```

Python SDK version updater

---

rust/ommx/src/convert/constraint.rs
rust/ommx/src/convert/instance.rs
rust/ommx/src/convert/parametric_instance.rs
rust/ommx/src/evaluate.rs

`ommx::v1::Function` is defined as following:
```rust
pub struct Function {
pub function: Option<Function>,
}
```
This `Option` is due to the `prost` compiles `oneof` in protobuf in this form.
Before this PR, `Function { function: None }` is regarded as invalid state, but it will be regarded as valid state and equals to `Funciton::zero()`.
Changes
--------
- `impl Evaluate for Function` returns `0.0` for `None` case
- `Instance::objective` and `Constraint::function` returns `Cow<Function>` instead of `Result<Function>`
- `impl Arbitrary for Instance, Constraint` generates `None` case.

Regard `None` for `ommx::v1::Function::function` as zero

---

rust/ommx/src/convert/constraint.rs
rust/ommx/src/convert/function.rs
rust/ommx/src/convert/instance.rs
rust/ommx/src/convert/linear.rs
rust/ommx/src/convert/polynomial.rs
rust/ommx/src/convert/quadratic.rs

Split from #162 
- Use `u32` for polynomial degree
- Fix `impl Arbitrary for Instance`. `max_degree` and `max_id` are reversed, bug of #163

Use `u32` for degree, fix `impl Arbitrary for Instance`

---

rust/ommx/src/convert/quadratic.rs

Found in #174 
This feature has been broken ever since it was introduced in #120.

`Quadratic::used_decision_variable_ids` not include IDs of `Linear` part

---

rust/ommx/src/convert/instance.rs

Penalty method translates constraint optimization problem
$$
\begin{align*}
\min & f(x) & \\
\text{s.t.} & g_i(x) &= 0 & \forall i
\end{align*}
$$
into parametrized unconstrained optimization problem
$$
\min f(x) + \sum_i \rho_i |g(x)|^2
$$
with parameters $\rho_i$. Using `ParametricInstance` intoduced #146, it can be represented as it is.

`Instance::penalty_method`

---

.github/actions/setup-test-environment/action.yml
.github/workflows/release_python.yml
python/ommx/pyproject.toml

- Use twine 5.1.1 for validating wheels until https://github.com/pypa/gh-action-pypi-publish/pull/309 is merged.
- twine 5.1.1 does not supports metadata 2.4, thus fix `maturin == 1.7.5` since it uses metadata 2.4 until 1.7.6 https://github.com/PyO3/maturin/issues/2335

Validate wheel with twine 5.1.1, fix to maturin 1.7.5

---

.github/workflows/rust.yml
Cargo.lock
Cargo.toml

As I said in #152
> Theoretically this should be major change in semver, but we update 1.2.0 instead of 2.0.0.
we should not introduce another rule for custom semantic versioning. We rather bump up major version as we break the compatibility as `cargo-semver-check` checks.
However, since current Rust SDK will require more breaking change until stable 2.0.0 release, I set the version to `2.0.0-rc.0`

Ready for Rust SDK 2.0.0 with release candidate

---

python/ommx/ommx/artifact.py

You can use another namespace for annotations via `annotation_namespace` argument.
```python
>>> builder = ArtifactBuilder.temp()
>>> desc = builder.add_dataframe(df, annotation_namespace="org.ommx.user2.", title="test_dataframe")
>>> print(desc.annotations)
{'org.ommx.user2.title': 'test_dataframe'}
```

Add `annotation_namespace` option to switch from `org.ommx.user.` to a custom namespace

---

rust/ommx/src/convert/constraint.rs
rust/ommx/src/convert/decision_variable.rs
rust/ommx/src/convert/instance.rs
rust/ommx/src/convert/parameter.rs
rust/ommx/src/evaluate.rs

- `Instance::evaluate` has changed to fill `substituted_value` in `DecisionVariable`s into `Soluiton.state`. This makes the partial substitution result more consistent.
- Revise proptest settings
- `String::arbitary` are replaced by `.{0,3}` for better test case generation
- Combinators used in `evaluate` and `partial_evaluate` tests are revised.

Fill `ommx.v1.Solution.state` with `substituted_value` of `DecisionVariable`

---

Taskfile.yml
python/ommx/docs/source/conf.py

sphinx/autoapi does not show inherited members by default. This PR adds a setting for it with some `Taskfile` update

Show inherited members in the Python SDK documentation

---

python/ommx/ommx/v1/__init__.py

Additional fix of #222. Since `__eq__` cannot be inherited, we have to manually override it.

Override `__eq__` method also for `Quadratic` and others

---

rust/ommx/src/convert/instance.rs
rust/ommx/src/evaluate.rs
rust/ommx/src/mps.rs
rust/ommx/src/mps/to_mps.rs

As a lot of solvers error out if the `BOUNDS` section includes unused variables, this PR updates the MPS output writer to only add variables that were actually used in the problem to the `BOUNDS` section. 
In this PR I also added a generic `anyhow::Error`→`MpsWriteError` conversion asn "Unknown Error", but this is mostly just to make the code compile. The method `used_variable_ids()` returns an `anyhow::Result`, but it doesn't seem to be able to produce any errors at all. Still, changing that method would be an API change so I decided to leave it as is. I added the error conversion instead of unwrapping just in case.

MPS: Only write used variables to output

---

python/ommx-pyscipopt-adapter/ommx_pyscipopt_adapter/ommx_to_pyscipopt.py
python/ommx-pyscipopt-adapter/tests/test_ommx_pyscipopt.py
python/ommx-python-mip-adapter/ommx_python_mip_adapter/ommx_to_python_mip.py
python/ommx-python-mip-adapter/ommx_python_mip_adapter/python_mip_to_ommx.py
python/ommx-python-mip-adapter/tests/test_model_to_instance.py

Fixes #199.
- ommx-pyscipopt-adapter's `model_to_solution` now checks the model status and updates the `Solution`'s optimality value accordingly if the solver deems it optimal.
- As we discussed, statuses other than "optimal" are left as `Optimality.UNSPECIFIED`. 
- To match the above, I moved the similar check the ommx-python-mip-adapter had from the `solve` function to that adapter's `model_to_solution`. There's no reason why only `solve` should perform that check.
- As `solve` calls `model_to_solution`, this does not change `solve`'s behavior

Get optimality from model in adapters' model_to_solution

---

proto/ommx/v1/instance.proto
proto/ommx/v1/parametric_instance.proto
python/ommx/ommx/v1/instance_pb2.py
python/ommx/ommx/v1/instance_pb2.pyi
python/ommx/ommx/v1/parametric_instance_pb2.py
python/ommx/ommx/v1/parametric_instance_pb2.pyi
rust/ommx/src/convert/instance.rs
rust/ommx/src/convert/parametric_instance.rs
rust/ommx/src/convert/sample_set.rs
rust/ommx/src/evaluate.rs
rust/ommx/src/ommx.v1.rs

Ready for binary encoding of integer variables.
- When an integer variable $x \in [0, 3]$ is binary encoded as $x = b_1 + 2 b_2$ with $b_1, b_2 \in \{0, 1\}$, $x$ will disappear from objective function and constraints.
- Thus, $x$ is not passed to solver which only solve with $b_1$ and $b_2$. So we have to reconstruct $x$ from $b_1$ and $b_2$, but how?
- `decision_variable_dependency` field in `ommx.v1.Instance` stores this relation, i.e. $x = b_1 + 2 b_2$ as a set of the ID of $x$ and a polynomial $b_1 + 2 b_2$.

Add `decision_variable_dependency` to represent polynomial dependency between decision variables

---

.github/actions/setup-test-environment/action.yml
python/ommx-python-mip-adapter/pyproject.toml
python/ommx/ommx/artifact.py
python/ommx/ommx/v1/__init__.py
python/ommx/ommx/v1/annotation.py
rust/ommx/src/artifact.rs
rust/ommx/src/artifact/annotations.rs
rust/ommx/src/artifact/builder.rs
rust/ommx/src/artifact/media_types.rs

Resolve #271 
- `Artifact.get_{sample_set, parametric_instance}` and `ArtifactBuilder.add_{sample_set, parametric_instance}` are added.
- These uses new media types `application/org.ommx.v1.sample-set` and `application/org.ommx.v1.parametric-instance`

`ommx.v1.{SampleSet, ParametricInstance}` support in OMMX Artifact

---

python/ommx-openjij-adapter/pyproject.toml
python/ommx-pyscipopt-adapter/pyproject.toml
python/ommx-python-mip-adapter/pyproject.toml
python/ommx/pyproject.toml

Bump versions to 1.8.0 to match the release of the Adapter base class and updates to the PySCIPOpt & Python-MIP APIs

Python SDK 1.8.0

---

Taskfile.yml
docs/en/Taskfile.yml
docs/ja/Taskfile.yml

Split the Taskfile.yml into separate files for `docs/ja` and `docs/en`.
* Add `Taskfile.yml` to `docs/ja` directory with tasks for building, opening, watching, and default.
* Add `Taskfile.yml` to `docs/en` directory with tasks for building, opening, watching, and default.
* Modify the root `Taskfile.yml` to include the new `Taskfile.yml` files from `docs/ja` and `docs/en`.
* Remove tasks related to `book_ja` and `book_en` from the root `Taskfile.yml`.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/Jij-Inc/ommx/pull/325?shareId=ef899e0d-b264-40c2-a26f-67d9350e4c33).

Split document Taskfile.yml

---

Cargo.lock

Fix build failure on https://github.com/Jij-Inc/ommx/actions/runs/13371964762/job/37342353111 due to tempfile 3.17.0 https://github.com/Stebalien/tempfile/pull/332

Update tempfile to 3.17.1, and other dependencies

---

rust/ommx/examples/create_artifact.rs
rust/ommx/src/convert/function.rs
rust/ommx/src/convert/instance.rs
rust/ommx/src/convert/linear.rs
rust/ommx/src/convert/polynomial.rs
rust/ommx/src/lib.rs
rust/ommx/src/mps/tests.rs
rust/ommx/src/random.rs
rust/ommx/src/random/constraint.rs
rust/ommx/src/random/decision_variable.rs
rust/ommx/src/random/function.rs
rust/ommx/src/random/instance.rs
rust/ommx/src/random/linear.rs
rust/ommx/src/random/parametric_instance.rs
rust/ommx/src/random/polynomial.rs
rust/ommx/src/random/quadratic.rs

Following up #330 
- Integrate `LinearParameters` and `QuadraticParameters` into `FunctionParameters`
- The number of terms generated with `num_terms` becomes `num_terms`, i.e. 
```rust
use ommx::{random::{FunctionParameters, random_deterministic}, v1::Function};
let f: Function = random_deterministic(FunctionParameters { num_terms: 5, max_degree: 3, max_id: 10 });
assert_eq!(f.into_iter().count(), 5);
```
- Update `InstanceParameters` to store the setting for objective and constraints separately.

Revise `Parameters` in `Arbitrary` trait

---

.github/workflows/release_python.yml
python/ommx-python-mip-adapter/ommx_python_mip_adapter/__init__.py

- Adds ommx-highs-adapter to the release workflow
- Fixes as a small papercut in ommx-python-mip-adapter where the exception type was not being exported in `__all__`

Prepare Python SDK 1.8.4 release

---

.github/workflows/doc.yml
LLMs.txt
docs/en/_toc.yml
docs/en/introduction.md
docs/en/tutorial/share_in_ommx_artifact.ipynb
docs/ja/introduction.md
docs/ja/tutorial/share_in_ommx_artifact.ipynb
python/ommx-highs-adapter/README.md
python/ommx-highs-adapter/Taskfile.yml
python/ommx-pyscipopt-adapter/Taskfile.yml
python/ommx-python-mip-adapter/Taskfile.yml

Split from #344
- Use `jupyter-book build --warningserror` (only) on CI
- Restore `markdown-code-runner` test, dropped accidentally on #327

Revise `jupyter-build` check

---

python/Taskfile.yml
python/ommx-highs-adapter/ommx_highs_adapter/adapter.py
python/ommx-openjij-adapter/ommx_openjij_adapter/__init__.py
python/ommx-openjij-adapter/tests/test_sample.py
python/ommx-pyscipopt-adapter/ommx_pyscipopt_adapter/adapter.py
python/ommx-python-mip-adapter/ommx_python_mip_adapter/adapter.py
python/ommx/ommx/adapter.py

Split from #344
- Introduce `ommx.adapter.SamplerAdapter`
- https://ommx--350.org.readthedocs.build/en/350/autoapi/ommx/adapter/index.html#ommx.adapter.SamplerAdapter
- Introduce `ommx_openjij_adapter.OMMXOpenJijSAAdapter` inheriting `SamplerAdapter`
- Mark `sample_qubo_sa` as `@deprecated`
- https://ommx--350.org.readthedocs.build/en/350/autoapi/ommx_openjij_adapter/index.html

Introduce `SamplerAdapter` and `OMMXOpenJijSAAdapter`

---

pyproject.toml
uv.lock

Follow up of #356 
Since `ruamel` is installed only via the head `script` section of `ci-scripts/setup-python-test-project.py`, but `pylance` does not see it.

Add ruamel-yaml to dev dependencies for LSP support

---

python/ommx/ommx/v1/__init__.py
rust/ommx/src/v1_ext/instance.rs

Since #369 converts inequality to inequality, the penalty method needs to support inequality.

Allow inequality constraints in penalty method

---

python/ommx-openjij-adapter/ommx_openjij_adapter/__init__.py
python/ommx-openjij-adapter/tests/test_sample.py
python/ommx/ommx/adapter.py
python/ommx/ommx/v1/__init__.py
rust/ommx/src/sorted_ids.rs

This pull request includes significant updates to the `python/ommx-openjij-adapter` and associated tests to enhance functionality and improve code quality. The key changes include the addition of new parameters for penalty weights, improvements in the sampling method, and extensive updates to the test cases.
Enhancements in `OMMXOpenJijSAAdapter`:
* Added new parameters `uniform_penalty_weight`, `penalty_weights`, and `inequality_integer_slack_max_range` to the `OMMXOpenJijSAAdapter` class and its methods to allow more flexible configuration of penalty weights. [[1]](diffhunk://#diff-5de2903ad8082b1b024e933271672f2303a4ea07dcd8e8608cf50641bec65d8aR51-R57) [[2]](diffhunk://#diff-5de2903ad8082b1b024e933271672f2303a4ea07dcd8e8608cf50641bec65d8aR73-R75) …

Use `to_qubo` in OpenJij Adapter

---

python/ommx-tests/tests/test_instance.py
python/ommx/ommx/v1/__init__.py

Bug description
---------------
`penalty_weight` option of `to_qubo` is passed to `ParametricInstance.with_parameters` directory. But this is not valid since the `with_parameters` requires `dict[parameter_id, weight]`, but we cannot get the `parameter_id` before `to_qubo` call. So we have to convert given `penalty_weight: dict[constraint_id, weight]` into `dict[parameter_id, weight]` by generated parameters while `to_qubo`.
Summary
--------
This pull request introduces a new test for the `to_qubo` method and updates the method to handle penalty weights more effectively. The changes ensure that the `to_qubo` method correctly interprets penalty weights provided in a dictionary form and applies them appropriately.
* Added `test_to_qubo_penalty_weight` to verify that `to_qubo` correctly …

`penalty_weight` option of `to_qubo` is broken

---

python/ommx-tests/tests/test_sample_set.py
python/ommx/ommx/v1/__init__.py

Resolve #393
```text
Type parameter "_T@list" is invariant, but "dict[int, int]" is not the same as "ToState"
Consider switching from "list" to "Sequence" which is covariant (reportArgumentType)
1 error, 0 warnings, 0 informations 
```
This PR replaces `list` to `Sequence`.

`ToSamples` type hint is broken for `list[dict[int, int]]` case

---

python/ommx/ommx/v1/__init__.py

Resolve #397
This pull request includes several changes to the `to_qubo` method in the `python/ommx/ommx/v1/__init__.py` file to handle maximization problems and improve the conversion between minimization and maximization problems. The most important changes include updating documentation, adding new functionality to convert problems back to maximization, and modifying the `as_minimization_problem` method to return a boolean.
* Updated documentation to clarify that the sense is converted to minimization for generating QUBO and then converted back to maximization.
* Added functionality to convert the instance back to a maximization problem after generating QUBO.
* Modified the `as_minimization_problem` method to return a boolean indicating whether the instance was converted. …

Restore maximize after `Instance.to_qubo`

---

python/ommx/ommx/v1/__init__.py

I attempted the following code and noticed that both instances introduced the same slack variables:
```python
import numpy as np
import jijmodeling as jm
x = jm.BinaryVar('x', shape=(2,))
problem = jm.Problem('example')
problem += jm.Constraint('c', -100*x[0] + x[1] <= 0)
instance = jm.Interpreter({}).eval_problem(problem)
qubo, const = instance.to_qubo()
instance2 = jm.Interpreter({}).eval_problem(problem)
qubo2, const2 = instance2.to_qubo(inequality_integer_slack_max_range = 31)
```
But I expect `instance2` to have the following variables:
I think we should pass `inequality_integer_slack_max_range` instead of hard-coded 32 to `Instance.add_integer_slack_to_inequality`.

Pass inequality_integer_slack_max_range to add_integer_slack_to_inequality instead of hard-coded 32

---

python/ommx-pyscipopt-adapter/ommx_pyscipopt_adapter/adapter.py
python/ommx-pyscipopt-adapter/tests/test_initial_state.py

* Add the feature of setting an initial state to `ommx_pyscipopt_adapter` by using the addSol method of PySCIPOpt.
* Add a test for the initial state in `test_initial_state.py`.

Add initial state support to ommx_pyscipopt_adapter

---

rust/ommx/benches/sum.rs
rust/ommx/src/random.rs

Fix bug in the benchmark code in #419. The fixed benchmark reproduces the performance issue that a summation of small linear functions costs $O(n^2)$.
This pull request refactors the random sampling mechanism in the benchmarking and random utilities of the `ommx` project. It introduces a new `Rng` type alias for `proptest::test_runner::TestRunner`, replaces the use of `random_deterministic` with `random` in benchmarks, and adjusts the parameters for some benchmark loops. Additionally, it removes an unused benchmark function and simplifies the `random` utility functions.
* Replaced the `random_deterministic` function with the new `random` function, which now accepts a mutable reference to `Rng`, in all benchmark functions (`sum_linear_*`, `sum_quadratic_*`, `sum_polynomial_*`, and …

Revise benchmarks and `ommx::random` API Design

---

python/ommx/src/evaluate.rs
python/ommx/src/instance.rs
python/ommx/src/message.rs
rust/ommx/benches/partial_evaluate.rs
rust/ommx/src/constraint/evaluate.rs
rust/ommx/src/decision_variable.rs
rust/ommx/src/evaluate.rs
rust/ommx/src/function/evaluate.rs
rust/ommx/src/instance/analysis.rs
rust/ommx/src/instance/arbitrary.rs
rust/ommx/src/mps.rs
rust/ommx/src/mps/to_mps.rs
rust/ommx/src/polynomial_base/evaluate.rs
rust/ommx/src/random/decision_variable.rs
rust/ommx/src/random/instance.rs
rust/ommx/src/random/parameter.rs
rust/ommx/src/random/parametric_instance.rs
rust/ommx/src/random/samples.rs
rust/ommx/src/random/state.rs
rust/ommx/src/v1_ext/constraint.rs
rust/ommx/src/v1_ext/function.rs
rust/ommx/src/v1_ext/instance.rs
rust/ommx/src/v1_ext/linear.rs
rust/ommx/src/v1_ext/parametric_instance.rs
rust/ommx/src/v1_ext/polynomial.rs
rust/ommx/src/v1_ext/quadratic.rs

Tasks
------
- Keep using `BTreeSet` because it makes the behavior easier for users to understand

Introduce `VariableIDSet` type

---

python/ommx/src/evaluate.rs
python/ommx/src/instance.rs
rust/ommx/benches/evaluate.rs
rust/ommx/benches/partial_evaluate.rs
rust/ommx/src/bound.rs
rust/ommx/src/constraint/evaluate.rs
rust/ommx/src/evaluate.rs
rust/ommx/src/function/evaluate.rs
rust/ommx/src/lib.rs
rust/ommx/src/polynomial_base/evaluate.rs
rust/ommx/src/v1_ext/constraint.rs
rust/ommx/src/v1_ext/function.rs
rust/ommx/src/v1_ext/instance.rs
rust/ommx/src/v1_ext/linear.rs
rust/ommx/src/v1_ext/parametric_instance.rs
rust/ommx/src/v1_ext/polynomial.rs
rust/ommx/src/v1_ext/quadratic.rs

- Add `atol` parameter in `Evaluate::{evaluate, evaluate_samples, partial_evaluate}`, and other API like `as_integer_bound`.

Add `atol` in `Evaluate`

---

rust/ommx/src/atol.rs
rust/ommx/src/bound.rs
rust/ommx/src/decision_variable.rs
rust/ommx/src/decision_variable/arbitrary.rs
rust/ommx/src/decision_variable/parse.rs
rust/ommx/src/instance/analysis.rs
rust/ommx/src/parse.rs
rust/ommx/src/v1_ext/instance.rs

Split from #459 
- `DecisionVariable` changed to impose the consistency condition for `kind` and `bound`.
- `kind` and `bound` are consistent if
- At least one possible value exists. For example, `kind=Integer` and `bound=[1.1, 1.9]` are inconsistent since there is no possible integer in the bound.
- The edge of bound must be integer for binary, integer, and semi-integer case.
Tasks
------

Kind-Bound consistency in `DecisionVariable`

---

.github/copilot-instructions.md
python/ommx/src/message.rs
rust/ommx/src/coefficient.rs
rust/ommx/src/format.rs
rust/ommx/src/function.rs
rust/ommx/src/function/add.rs
rust/ommx/src/function/mul.rs
rust/ommx/src/lib.rs
rust/ommx/src/polynomial_base.rs
rust/ommx/src/polynomial_base/add.rs

Use Rust-idiomatic `ommx::Function` in Python SDK's `ommx._ommx_rust.Function`

---

Cargo.lock
Cargo.toml
python/ommx-highs-adapter/pyproject.toml
python/ommx/ommx/_ommx_rust.pyi
python/ommx/pyproject.toml

- Though PyO3 0.25 has been released, `serde-pyobject` does not support it yet
- `pyo3-stub-gen` is upgraded to 0.8.2, not 0.9.1 since it have some problem.

Update PyO3 to 0.24

---

PYTHON_SDK_MIGRATION_GUIDE.md
python/ommx-highs-adapter/ommx_highs_adapter/adapter.py
python/ommx-pyscipopt-adapter/ommx_pyscipopt_adapter/adapter.py
python/ommx-python-mip-adapter/ommx_python_mip_adapter/adapter.py
python/ommx-python-mip-adapter/tests/test_model_to_instance.py
python/ommx-tests/tests/test_instance.py
python/ommx-tests/tests/test_mps.py
python/ommx/ommx/_ommx_rust.pyi
python/ommx/ommx/v1/__init__.py
python/ommx/src/instance.rs

Changes
--------
Same changes are taken also for `constraints`, `removed_constraints` and `parameters` in `ParametricInstance`.
- `decision_variables` property is changed to return `list[DecisionVariable]` instead of `dict[int, DecisionVariable]`, and assures sorted by the ID.
- `get_decision_variable_by_id(id)` method is added
- `Instance.decision_variables` property gets suffix `decision_variables_df`
- This returns `pandas.DataFrame`, most data scientists calls it `df`.
- `Instance.get_decision_variables` method becomes `decision_variables` property
- `Instance.get_decision_variable(id)` is renamed to `get_decision_variable_by_id` and uses `raw.get_decision_variable_by_id(id)`
- `ParametricInstance.get_decision_variable(id)` still search ID linearly. This will be fixed next PR.

Revise `Instance.get_decision_variables` and related APIs

---

rust/ommx/src/decision_variable.rs
rust/ommx/src/instance/analysis.rs
rust/ommx/src/solution/parse.rs

For integer variable, `1.000000001` is consistent, but `0.99999999999` becomes inconsistent wrongly.

Bug in substituted value consistency check

---

python/ommx/ommx/v1/__init__.py
rust/ommx/src/mps/format.rs

This PR improves the MPS format output to properly handle infinite bounds using standard MPS specifiers and adds comprehensive unit tests.
1. **Add `compress` parameter to `Instance.save_mps()` method** 
- Allows users to optionally disable gzip compression when saving MPS files
- Default is `compress=True` to maintain backward compatibility
2. **Fix infinite bound representation in MPS format**
- Previously, infinite bounds were written as literal `inf` and `-inf` values, which is not standard MPS format
- Now uses proper MPS bound specifiers:
- `FR` (free) for unbounded variables `(-inf, +inf)`
- `PL` (plus infinity) for variables with upper bound = `+inf`
- `MI` (minus infinity) for variables with lower bound = `-inf`
- Finite bounds continue to use `UP`/`LO` (continuous) or `UI`/`LI` …

MPS output does not handle `f64::INFINITY` in `Bound` correctly

---

python/ommx-highs-adapter/ommx_highs_adapter/adapter.py
python/ommx-pyscipopt-adapter/ommx_pyscipopt_adapter/adapter.py
python/ommx/ommx/v1/__init__.py
rust/ommx/src/bound.rs

Resolve #510. The root cause is `f64::ceil` keeps its sign, e.g. `(-0.1_f64).ceil()` returns `-0.0` instead of `0.0`.

Normalize `-0.0` to `0.0` in `Bound`

---

python/ommx-openjij-adapter/ommx_openjij_adapter/__init__.py
python/ommx-openjij-adapter/tests/test_sample.py

- When sampling maximization problems with the openjij adapter, the objective function values were being returned negative when they should be positive, and vice versa.
- This was due to converting them to minimization problems when generating qubo/hubo, but never converting back before evaluating the results.

openjij: Fix inverted sign in obj function in maximization problems
